### ISSUE TITLE
Segmentation error using splitsh-lite binary v1.0.1

### ISSUE THREAD

**Issue by Spomky** [splitsh/lite#35]
Hi,

I have the following error when I try to run the binary for the first time.
This error does not occur when I run the app again.

Any idea?

```sh
unexpected fault address 0x7f7641ae4008
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7f7641ae4008 pc=0x4d3cd9]

goroutine 1 [running]:
runtime.throw(0x65d770, 0x5)
        /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc42004b8c0 sp=0xc42004b8a0
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:297 +0x28c fp=0xc42004b910 sp=0xc42004b8c0
github.com/boltdb/bolt.(*Cursor).search(0xc42004bab8, 0xc42000c560, 0x14, 0x20, 0x4)
        /go/src/github.com/boltdb/bolt/cursor.go:255 +0x69 fp=0xc42004b9d8 sp=0xc42004b910
github.com/boltdb/bolt.(*Cursor).seek(0xc42004bab8, 0xc42000c560, 0x14, 0x20, 0x0, 0x0, 0x42bd12, 0x9552c0, 0x7f7641bd0000, 0x0, ...)
        /go/src/github.com/boltdb/bolt/cursor.go:159 +0xb1 fp=0xc42004ba28 sp=0xc42004b9d8
github.com/boltdb/bolt.(*Bucket).Bucket(0xc4200a40f8, 0xc42000c560, 0x14, 0x20, 0xc42004bb20)
        /go/src/github.com/boltdb/bolt/bucket.go:112 +0x108 fp=0xc42004bae8 sp=0xc42004ba28
github.com/boltdb/bolt.(*Tx).Bucket(0xc4200a40e0, 0xc42000c560, 0x14, 0x20, 0xc42001c0c0)
        /go/src/github.com/boltdb/bolt/tx.go:101 +0x4f fp=0xc42004bb20 sp=0xc42004bae8
github.com/splitsh/lite/splitter.(*cache).getHead.func1(0xc4200a40e0, 0x667400, 0xc4200a40e0)
        /go/src/github.com/splitsh/lite/splitter/cache.go:80 +0x72 fp=0xc42004bbd8 sp=0xc42004bb20
github.com/boltdb/bolt.(*DB).View(0xc42009e000, 0xc42004bc50, 0x0, 0x0)
        /go/src/github.com/boltdb/bolt/db.go:629 +0x9f fp=0xc42004bc28 sp=0xc42004bbd8
github.com/splitsh/lite/splitter.(*cache).getHead(0xc42001a930, 0x667a08)
        /go/src/github.com/splitsh/lite/splitter/cache.go:85 +0x66 fp=0xc42004bc78 sp=0xc42004bc28
github.com/splitsh/lite/splitter.(*state).pushRevs(0xc420058230, 0xc420014a50, 0x0, 0x0)
        /go/src/github.com/splitsh/lite/splitter/state.go:538 +0x235 fp=0xc42004bd08 sp=0xc42004bc78
github.com/splitsh/lite/splitter.(*state).walker(0xc420058230, 0x6675b0, 0xc420058230, 0xed16c37a9)
        /go/src/github.com/splitsh/lite/splitter/state.go:169 +0xf3 fp=0xc42004bd78 sp=0xc42004bd08
github.com/splitsh/lite/splitter.(*state).split(0xc420058230, 0x0, 0x0)
        /go/src/github.com/splitsh/lite/splitter/state.go:120 +0xa5 fp=0xc42004be28 sp=0xc42004bd78
github.com/splitsh/lite/splitter.Split(0xc420092140, 0xc42001c500, 0x0, 0x0)
        /go/src/github.com/splitsh/lite/splitter/config.go:51 +0x93 fp=0xc42004be68 sp=0xc42004be28
main.main()
        /go/src/github.com/splitsh/lite/main.go:103 +0x1ed fp=0xc42004bf88 sp=0xc42004be68
runtime.main()
        /usr/local/go/src/runtime/proc.go:185 +0x20a fp=0xc42004bfe0 sp=0xc42004bf88
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42004bfe8 sp=0xc42004bfe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 6 [runnable]:
main.main.func1(0xc42001c540, 0xc42001c500)
        /go/src/github.com/splitsh/lite/main.go:97 +0x78
created by main.main
        /go/src/github.com/splitsh/lite/main.go:100 +0x50e
```

**Comment by Spomky** [comment]
Closing for inactivity
